// Generated by scripts/capture-movement.mts --write. Lists every movement in this folder.
import type { Movement } from "../types";
import boxJump from "./box-jump.json";
import dropJump from "./drop-jump.json";
import nordicHamstringCurl from "./nordic-hamstring-curl.json";

export const ALL = [boxJump, dropJump, nordicHamstringCurl] as unknown as Movement[];
